spring:
  profiles:
    active: dev
  thymeleaf:
    mode: HTML
  devtools:
    restart:
      trigger-file: .trigger



book:
  name: 動物世界
  author: 凱倫強
  isbn: ${random.uuid}
  description: ${book.name}, 這本書還不錯
